---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager-user-workload-api-read-binding-{{ .Release.Namespace }}
  namespace: openshift-user-workload-monitoring 
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: monitoring-alertmanager-api-reader 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-thanos-{{ .Release.Namespace }}-alerts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
---
# This ClusterRoleBinding allows grafana-sa-token SA to access metrics from the OpenShift user
# workload monitoring stack.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitoring-view-thanos-{{ .Release.Namespace }}-alerts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
---
# This ClusterRoleBinding allows grafana-sa-token SA to access metrics from the built-in OpenShift
# cluster monitoring stack, required for accessing core OpenShift metrics and monitoring data
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-cluster-monitoring-view-thanos-{{ .Release.Namespace }}-alerts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-prometheus-reader-binding-{{ .Release.Namespace }}-alerts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-prometheus-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}