{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  endpoints:
  - port: http
    interval: {{ .Values.monitoring.interval | default "30s" }}
    path: {{ .Values.monitoring.path | default "/metrics" }}
    scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | default "10s" }}
{{- end }}