apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-dashboard
  namespace: llama-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-dashboard
  template:
    metadata:
      labels:
        app: ai-dashboard
    spec:
      containers:
        - name: app
          image: quay.io/ecosystem-appeng/metric-ui:0.14
          ports:
            - containerPort: 8501
          env:
            - name: DEEPINFRA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deepinfra-secret
                  key: api-key
