# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-dashboard
  labels:
    app: ai-dashboard
spec:
  selector:
    app: ai-dashboard
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
