image:
  repository: quay.io/ecosystem-appeng/metric-ui
  tag: ah29
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8501

env:
  PROMETHEUS_URL: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
  LLM_URL: "http://llm-service:8012"
  LLM_API_TOKEN: ""
  METRICS_API_URL: "http://metrics-api-svc.{{ .Release.Namespace }}.svc.cluster.local:8000"
