name: Build and push image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  METRICS_API_DIR: src/api

jobs:
  build-image:
    name: Build and Push container image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: metrics-api
            context: src
            dockerfile: src/api/Dockerfile
            image-name: metrics-api
          - name: metric-ui
            context: src/ui
            dockerfile: src/ui/Dockerfile
            image-name: metric-ui
          - name: metric-alerting
            context: src/alerting
            dockerfile: src/alerting/Dockerfile
            image-name: metric-alerting


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set version from run number
        id: version
        run: |
          echo "tag=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: quay.io/ecosystem-appeng/${{ matrix.image-name }}:${{ steps.version.outputs.tag }}
          build-args: |
            IMAGE_TAG=${{ steps.version.outputs.tag }}
